### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by pathcl** [reorx/params#1]
There are weird inconsistencies regarding exception handling:

> rumanio:ezmomi cosmonautas$ pip3 list |grep -i params
> params (0.2.1)
> 
> rumanio:ezmomi cosmonautas$ grep -r -i except /usr/local/lib/python3.6/site-packages/params/
> Binary file /usr/local/lib/python3.6/site-packages/params//contrib/__pycache__/django.cpython-36.pyc matches
> Binary file /usr/local/lib/python3.6/site-packages/params//contrib/__pycache__/tornado.cpython-36.pyc matches
> /usr/local/lib/python3.6/site-packages/params//contrib/django.py:    except Exception as e:
> /usr/local/lib/python3.6/site-packages/params//contrib/tornado.py:        except Exception as e:
> /usr/local/lib/python3.6/site-packages/params//core.py:class InvalidParams(Exception):
> /usr/local/lib/python3.6/site-packages/params//core.py:            except Exception as e:
> /usr/local/lib/python3.6/site-packages/params//core.py:                except ValueError, e:
> /usr/local/lib/python3.6/site-packages/params//core.py:                        except ValueError, e:
> /usr/local/lib/python3.6/site-packages/params//core.py:            except ValueError, e:
> /usr/local/lib/python3.6/site-packages/params//fields.py:            except UnicodeDecodeError:
> /usr/local/lib/python3.6/site-packages/params//fields.py:                except ValueError as e:
> /usr/local/lib/python3.6/site-packages/params//fields.py:                except ValueError as e:
> /usr/local/lib/python3.6/site-packages/params//fields.py:        except ValueError, e:
> /usr/local/lib/python3.6/site-packages/params//fields.py:        except ValueError:

> rumanio:ezmomi cosmonautas$ python3
> Python 3.6.0 (default, Dec 24 2016, 00:01:50)
> [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>>

Why not always use 'as' ?. This breaks compatibility on python 3.6.0 at least

**Comment by reorx** [comment]
My bad, some of the code are lack of maintenance since they were written, thanks for resolving them😀

**Comment by reorx** [comment]
I'll check to make sure everything is py3 compatible before this issue closed

**Comment by reorx** [comment]
params is now python 3 compatible in latest version 0.4.2
